### ISSUE TITLE
CONTRIBUTING.rst references 'stackhut-tool' instead of 'stackhut-common'

### ISSUE THREAD

**Issue by mands** [stackhut/stackhut#13]
_From @collingreen on September 21, 2015 2:44_

TODO:
- [ ] update to match current project
- [ ] verify steps and tools fully work

_Copied from original issue: StackHut/stackhut-common#2_

**Comment by mands** [comment]
Yes! Absolutely need to updating contributing process - we're all about those PRs :) Will work on this week...

**Comment by collingreen** [comment]
Feel free to ping me if you want third party eyes on an RC
